#!bin/zsh

# delete the cloudwatch rule after deleting the cloudwatch rule target
function ctdelr(){
  # examples:
  # ctfilter 2020 | ctdelr
  # ctfilter 202103 | ctdelr
  # parallel aws events remove-targets --rule {} --ids 1
  # to use, run this command: ctfilter 2020 | ctdelr
  parallel aws events delete-rule --name {}
}
