#!bin/zsh

# TODO: how to remove target and delete rule in a single function?
# delete the cloudwatch rule target before deleting it
# run ctfilter ... | ctdelt, then run
# run ctfilter ... | ctdelr
function ctdelt(){
  # examples:
  # ctfilter 2020 | ctdelt
  # ctfilter 202103 | ctdelt
  parallel aws events remove-targets --rule {} --ids 1
  # parallel aws events delete-rule --name {}
}
