#!bin/zsh

function aqp(){
  # purge sqs queue
  # aqp -l to purge local queue
  local localOpt queueUrl
  while getopts 'l' opt; do
    case "$opt" in
      l) localOpt=true;;
    esac
  done
  shift $(($OPTIND - 1))

  if [ $localOpt ]; then
    queueUrl=$AWS_LOCAL_QUEUE
    echo purging $queueUrl
    aws --endpoint-url $AWS_LOCAL_QUEUE_ENDPOINT sqs purge-queue --queue-url $queueUrl
  else
    queueUrl=${1:-$AWS_QUEUE_URL}
    echo purging $queueUrl
    aws sqs purge-queue --queue-url $queueUrl
  fi

}
