#!bin/zsh

function aqp(){
  # purge sqs queue
  # aqp -l <queueName>  to purge local queue
  local localOpt queueUrl
  while getopts 'l' opt; do
    case "$opt" in
      l) localOpt=true;;
    esac
  done
  shift $(($OPTIND - 1))

  local queueName=$1

  if [ $localOpt ]; then
    echo purging $queueUrl
    aws sqs --endpoint-url $AWS_LOCAL_QUEUE_ENDPOINT purge-queue --queue-url http://localhost:9324/queues/$queueName
  else
    queueUrl=${1:-$AWS_QUEUE_URL}
    echo purging $queueUrl
    aws sqs purge-queue --queue-url $queueUrl
  fi

}
