#!bin/zsh

function aqr(){
  # receive sqs message
  # aqr <queue-url>
  local localOpt
  while getopts 'l' opt; do
    case "$opt" in
      l) localOpt=true;;
    esac
  done
  shift $(($OPTIND - 1))

  local queueUrl=${1:-$AWS_QUEUE_URL}

  if [ -n "$localOpt" ]; then
    echo getting $AWS_LOCAL_QUEUE
    aws --endpoint-url $AWS_LOCAL_QUEUE_ENDPOINT sqs receive-message --queue-url $AWS_LOCAL_QUEUE --attribute-names All --message-attribute-names All
  else
    aws sqs receive-message --queue-url $queueUrl --attribute-names All --message-attribute-names All
  fi
}
