#!bin/zsh

function jqlist(){
  # print a list of item names from the json
  # examples:
  # jqlist -n title - sort by property title, assume there is an array in .Items
  # jqlist -n title -a Items - sort by property title in .Items
  #
  # options:
  #
  # -c : (collection) path to the array in the json eg if the json contains an array in .Items,
  # supply -a Items
  #
  # -n : name of the property to display in the output 

  local itemName
  local arrayPath="Items"

  local defaultActiveFilter
  local active=
  while getopts 'c:n:a' opt; do
    case "$opt" in
      c) arrayPath=$OPTARG;;
      # n) itemName=$OPTARG;;
      a) active=true;;
    esac
  done
  shift $(($OPTIND - 1))

  local activeFilter
  # [[ -n $active ]] && activeFilter='select(.active == 1) |'

  # sort_by only operates on arrays
  # assume that .Items is an array
  # jq --raw-output ".$arrayPath | sort_by(.$itemName) | .[] | "$activeFilter".$itemName" $1
  jq --raw-output ".$arrayPath | sort_by(.$itemName) | .[] | {.name,.active} " $1
}
