# set up the fzf directory switcher
# specify the bindkey for the ud function
# ud is a fzf directory switcher
# the fzf preview window previews the directory/file contents
# the depth of the directory preview can be configured with the options key
# TODO: add namespaces, don't restrict to just ud
# TODO: add ignore glob options (use exa -i)
# TODO: cache edited files with nvim

keymaps:
  # XDG folders
  # config
  - bindkey: c #udc opens fzf and lists its directory contents
    dir: $XDG_CONFIG_HOME
    options: 5
  - bindkey: cn
    dir: $XDG_CONFIG_HOME/nvim
    options: 5
  - bindkey: ca
    dir: $XDG_CONFIG_HOME/zsh/aliases
    options: 5
  # lib
  - bindkey: l
    dir: $HOME/.local/lib
    options: 5
  # data
  - bindkey: xd
    dir: $XDG_DATA_HOME
    options: 4
  # state
  - bindkey: xs
    dir: $XDG_STATE_HOME
    options: 2
  # cache
  - bindkey: xc
    dir: $XDG_CACHE_HOME
  # bin
  - bindkey: xb
    dir: $HOME/.local/bin

  - bindkey: k
    dir: $HOME/certis/docs/wiki
    options: 4

  # my dotfiles
  - bindkey: z
    dir: $HOME/.dotfiles
    options: 4

  # other folders
  - bindkey: tl
    dir: $HOME/Downloads

  # docs
  - bindkey: d
    dir: $HOME/docs
    options: 3

  # tmp folders
  - bindkey: t # tmP
    dir: /tmp
    options: 3
  - bindkey: tc
    dir: /tmp/certify-verifysync
  - bindkey: tcr
    dir: /tmp/certify-verifysync/report

  - bindkey: scu # State Certify Users - sap s3 uploads
    dir: $_CERTIFY_S3_BUCKET_SAP_SYNC_LOCAL_FOLDER

  # read the src
  - bindkey: s
    dir: $HOME/src
  - bindkey: sc
    dir: $HOME/src/candy
    options: 1 # specify how deep the directory preview should be
  - bindkey: sm
    dir: $HOME/src/me
    options: 3
  - bindkey: so
    options: 2
    dir: $HOME/src/open

  # my projects
  - bindkey: w # my website
    dir: $HOME/src/me/website/docs
    options: 5 # specify how deep the directory preview should be

  # (ノ ゜Д゜)ノ ︵ ┻━┻ flipping playground
  - bindkey: dp # my website
    dir: $HOME/dev/playground
    options: 3 # specify how deep the directory preview should be
