#!/bin/zsh

function asar(){
  # aws sts assume-role
  # if assume role is gated by mfa access, then you have to manually set the env variables from aws sts get-session-token before calling this function

  local data=$(aws sts assume-role --role-arn arn:aws:iam::***REMOVED*** --role-session-name test)
  local accessKey=$(jq --raw-output '.Credentials.AccessKeyId' <<< $data)
  local secret=$(jq --raw-output '.Credentials.SecretAccessKey' <<< $data)
  local token=$(jq --raw-output '.Credentials.SessionToken' <<< $data)

  echo -e $fg[green] setting aws env vars '...'

  export AWS_ACCESS_KEY_ID=$accessKey
  export AWS_SECRET_ACCESS_KEY=$secret
  export AWS_SESSION_TOKEN=$token
}

