#!/bin/zsh

function acdc(){
  # aws ecs describe-clusters
  # accd <clusterName>

  local verbose cluster
  while getopts 'v' opt; do
    case "$opt" in
      v) verbose=true;;
    esac
  done
  shift $(($OPTIND - 1))

  cluster=${cluster:-StagingCluster}

    local jqQuery=$(cat <<-EOF
   include "pad";
   include "colour";
   .
EOF
)

  local result=$(aws ecs describe-clusters --clusters $cluster)

  if [ -n "$verbose" ]; then
    jq --raw-output -L "~/.config/jq" "." <<< $result
  else
    jq --raw-output -L "~/.config/jq" "$jqQuery" <<< $result
  fi
}
