#!/bin/zsh

function acdsf(){
  # aws ecs describe services fuzzy
  # acdsf -n <eventsToShow>
  # acdsf -c <cluster= d|s|p>
  # -d debug - view command to be run
  local number clusterOpt plain debug

  while getopts 'n:c:pd' opt; do
    case "$opt" in
      n) number=$OPTARG;;
      c) clusterOpt=$OPTARG;;
      p) plain="-p";;
      d) debug=true;;
    esac
  done
  shift $(($OPTIND - 1))

  number=${number:-2}
  clusterOpt=${clusterOpt:-s}

  local results=$(acls -c $clusterOpt | fzf | join-lines)
  [ -n "$debug" ] && echo running command:>&2
  [ -n "$debug" ] && echo acds $plain -n $number -c $clusterOpt $results >&2
  [ -n "$results" ] && acds $plain -n $number -c $clusterOpt $results
} 
