#!bin/zsh

function fsync(){
  # --archive, -a            archive mode is -rlptgoD (no -A,-X,-U,-N,-H)
  # --recursive, -r          recurse into directories
  # --links, -l              copy symlinks as symlinks
  # --perms, -p              preserve permissions
  # --times, -t              preserve modification times
  # --group, -g              preserve group
  # --owner, -o              preserve owner (super-user only)
  # -D                       same as --devices --specials
  # --devices                preserve device files (super-user only)
  # --specials               preserve special files

  # delete - remove files in target that do not belong in source
  # -v - verbose
  # -P - progress bar
  # --quiet - don't show non-error messages
  # --stats - show a summary of changes

  mkdir -p /Volumes/penwhel/tim/local/share/data

  # Risk: what if i rysync wrongly and delete my home folder?
  rsync -aP --stats --delete --exclude node_modules --exclude tmp ~/dotfiles ~/dev ~/src ~/docs ~/Dropbox ~/Desktop /Volumes/penwhel/tim

  rsync -aP --stats --delete ~/local/bin /Volumes/penwhel/tim/local
  # backup passwordstore and gpg
  rsync -aP --stats --delete ~/.local/share/pass ~/.local/share/gnupg /Volumes/penwhel/tim/local/share
}
