#!bin/zsh

function fsync(){
  # --archive, -a            archive mode is -rlptgoD (no -A,-X,-U,-N,-H)
  # --recursive, -r          recurse into directories
  # --links, -l              copy symlinks as symlinks
  # --perms, -p              preserve permissions
  # --times, -t              preserve modification times
  # --group, -g              preserve group
  # --owner, -o              preserve owner (super-user only)
  # -D                       same as --devices --specials
  # --devices                preserve device files (super-user only)
  # --specials               preserve special files

  # delete - remove files in target that do not belong in source
  # -v - verbose
  # -P - progress bar
  # --quiet - don't show non-error messages
  # --stats - show a summary of changes

  local destination=/Volumes/penwhel/tim

  while getopts 'n' opt; do
    case "$opt" in
      n) destination='tim@tardis:~/nsync';;
    esac
  done
  shift $(($OPTIND - 1))

  mkdir -p $destination/local/share/data
  mkdir -p $destination/Documents

  # dotfiles, src
  rsync -aP --stats --delete --exclude node_modules --exclude tmp ~/dotfiles ~/src ~/Desktop $destination

  # Documents
  rsync -aP --stats --delete  ~/Documents/candy ~/Documents/dropbox  $destination/Documents

  # Pictures
  rsync -aP --stats --delete "$HOME/Pictures/Photos Library.photoslibrary" "$HOME/Pictures/Photo Booth Library" ~/Pictures/Snagit $destination/Pictures

  # binaries
  rsync --progress -aP --stats --delete ~/.local/bin $destination/local

  # backup passwordstore and gpg
  rsync -aP --stats --delete ~/.local/share/pass ~/.local/share/gnupg $destination/local/share
  
  # backup zsh history $HISTFILE
  rsync -aP --stats --delete ~/.local/state/zsh $destination/local/state/

  # backup elasticmq binary
  rsync -aP --stats --delete ~/.local/share/elasticmq $destination/local/share/
}
