# set up the fzf directory switcher
# the fzf preview window previews the directory/file contents
# the depth of the directory preview can be configured with the depth key
# TODO: add namespaces, don't restrict to just ud

# run _fsc and zsh-compile-functions to compile changes
keymaps:
  # XDG_CONFIG DIRS - Top Row
  - [f, $HOME/dotfiles/bin]
  - ["ff", $XDG_BIN]
  - [g, $XDG_DATA_HOME, 3]
  # local nvim runtime
  - [gn, $XDG_DATA_HOME/nvim, 5]
  # homebrew nvim runtime
  - [gnn, /opt/homebrew/opt/neovim/share/nvim/runtime, 5]
  - [gnm, $XDG_DATA_HOME/nvim/mason, 5]
  - [c, $XDG_CONFIG_HOME, 5]
  - [cn, $HOME/dotfiles/config/nvim, 5]
  - [cnn, $XDG_CONFIG_HOME/nvim, 5]
  - [ca, $XDG_CONFIG_HOME/zsh/aliases, 5]
  - [r, $XDG_CACHE_HOME, 2]
  - [l, $HOME/dotfiles/lib, 7]
  # - [th, $HOME/dotfiles/templates]
  - bindkey: td
    dir: $HOME/dotfiles/lib/zsh/candy/templates
    depth: 3
    show-hidden: true
    show-ignore: true
  - ["l,", $HOME/.local/lib, 7]
  - [xs, $XDG_STATE_HOME, 5]
  # Home Row
  - [h, $HOME/src/me, 4, \\.git$, true, true, dirname | xargs dirname] # this yml file is converted to json. a backslash is an escape character in json. we need to escape the backslash. we want to pass \.git$ as the regex filter to fd
  - [ht, $HOME/src/me/nvim]
  - [htn, $HOME/src/me/nvim/git-worktree.nvim]
  - [hc, $HOME/src/me/zsh/candy]
  - [t, $HOME/src/playground, 5, \\.git$, true, true, dirname | xargs dirname]
  - [n, $HOME/src/clones, 4, \\.git$, true, true, dirname | xargs dirname]
  - [s, $HOME/src]
  # Bottom row
  - [w, $HOME/src/me/wiki, 8]
  - [v, $HOME/Documents/candy/wiki, 5]

  - [k, $HOME/Desktop]

  # trash
  - [q, $HOME/.Trash]
  - [p, /tmp]
  - [tl, $HOME/Downloads]

  # SRC
  - [d, $HOME/src/candy/db]
  - [s., $HOME/src/candy/referralcandy-main/main, 5]
  - ["s,", $HOME/src/candy/main/referralcandy-main, 5]
  - [sd, $HOME/src/candy/main/referralcandy-main/packages/daemons]
  - [
      sdb,
      $HOME/src/candy/referralcandy-main/main/packages/api/database_migrations/api,
    ]
  - [
      sdbf,
      $HOME/src/candy/referralcandy-main/feature/packages/api/database_migrations/api,
    ]
  - [se, $HOME/src/candy/main/referralcandy-main/packages/external-api, 5]
  - [si, $HOME/src/candy/main/referralcandy-main/packages/infra, 5]
  - [
      s..,
      $HOME/src/candy/main/referralcandy-main/packages/common-services/scripts,
    ]

  - [tg, $HOME/dotfiles/config/nvim/lua/tg]
  # Candy playground
  - [tw, $HOME/src/playground/playwright]
  - [th, $HOME/src/playground/playwright-script]
  - [ta, $HOME/src/playground/candy/github-actions/]
  - [tgpa, $HOME/src/playground/candy/github-public-actions/]
  - [ts, $HOME/src/playground/candy/candyStore/embedded-signup]
  - [tp, $HOME/src/playground/candy/candyStore/post-purchase-popup/]
  - [tr, $HOME/src/playground/candy/candyStore/referral-widget/]
  - [tj, $HOME/src/playground/candy/candyStore/js-integration/]

  # OLD CANDY
  - [st, $HOME/src/candy/old/customer-tracks/]
  - [sb, $HOME/src/candy/old/business]
  - [sc, $HOME/src/candy, 5, \\.git$, true, true, dirname | xargs dirname]
  # oops sh will create zsh shortcut which shadows zsh bin
  # - [sh, $HOME/src/candy/main/referralcandy-main/packages/daemons]
  - [so, $HOME/src/candy/old]
  - [soi, $HOME/src/candy/old/referralcandy-integration-events]
  - [soc, $HOME/src/candy/old/composer]
  - [sp, $HOME/src/candy/old/pentel]
  - [sp2, $HOME/src/candy/pentel]
  - [sr, $HOME/src/candy/old/referral_corner]
  - [sm, $HOME/src/candy/old/candymail]
  - [sw, $HOME/src/candy/old/webapp/]

  # /etc
  - [en, /etc/nginx]
  - [el, /etc/letsencrypt]
  - [ed, /etc/dovecot]

  # /var
  - [al, /var/log]
  - [aln, /var/log/nginx]
