# set up the fzf directory switcher
# specify the bindkey for the ud function
# ud is a fzf directory switcher
# the fzf preview window previews the directory/file contents
# the depth of the directory preview can be configured with the depth key

# NOTE:
# . alias - search files
# : alias - go to dir immediately

# TODO: add namespaces, don't restrict to just ud
# TODO: cache edited files with nvim

keymaps:
  # XDG folders
  # config
  - bindkey: c #udc opens fzf and lists its directory contents
    dir: $XDG_CONFIG_HOME
    depth: 5
  - bindkey: cn
    dir: $XDG_CONFIG_HOME/nvim
    depth: 5
  - bindkey: ca
    dir: $XDG_CONFIG_HOME/zsh/aliases
    depth: 5
  # lib
  - bindkey: l
    dir: $HOME/.local/lib
    depth: 5
  # data
  - bindkey: g
    dir: $XDG_DATA_HOME
    depth: 4
  # state
  - bindkey: xs
    dir: $XDG_STATE_HOME
    depth: 5
  # cache
  - bindkey: r
    dir: $XDG_CACHE_HOME
    depth: 3
  # bin
  - bindkey: f
    dir: $HOME/.local/bin

  - bindkey: k
    dir: $HOME/certis/docs/wiki
    depth: 4

  # my dotfiles
  - bindkey: z
    dir: $HOME/.dotfiles
    depth: 4

  # other folders
  - bindkey: tl
    dir: $HOME/Downloads

  # docs
  - bindkey: d
    dir: $HOME/Documents
    depth: 2
  - bindkey: v # candy wiki
    dir: $HOME/Documents/candy/wiki
    depth: 5 # specify how deep the directory preview should be

  # tmp folders
  - bindkey: p # tmp
    dir: /tmp
    depth: 3

  # ⊙▽⊙ read the src
  - bindkey: s
    dir: $HOME/src
  - bindkey: s.
    dir: $HOME/src/candy/main/referralcandy-main
    depth: 5 # specify how deep the directory preview should be
  - bindkey: sp
    dir: $HOME/src/candy/old/pentel
  - bindkey: sc
    dir: $HOME/src/candy
    depth: 5 # specify how deep the directory preview should be
    glob: \\.git$
    show-hidden: true
    show-ignore: true
    xargs: dirname
  - bindkey: h
    dir: $HOME/src/me
    depth: 4
    glob: \\.git$ # this yml file is converted to json. a backslash is an escape character in json. we need to escape the backslash. we want to pass \.git$ as the regex filter to fd
    show-hidden: true
    show-ignore: true
    xargs: dirname # use xargs to further filter ouput
  - bindkey: hc
    dir: $HOME/src/me/zsh/candy
  - bindkey: ht
    dir: $HOME/src/me/zsh/candy/klaviyo/
  - bindkey: hn
    dir: $HOME/src/me/zsh/candy/shopify/
  - bindkey: n
    depth: 4
    dir: $HOME/src/clones
    glob: \\.git$
    show-hidden: true
    show-ignore: true
    xargs: dirname
  # ＼（＾ ＾）／ my projects
  - bindkey: w # my website
    dir: $HOME/src/me/wiki
    depth: 5 # specify how deep the directory preview should be
  # (ノ ゜Д゜)ノ ︵ ┻━┻ flipping playground
  - bindkey: t
    depth: 5
    dir: $HOME/src/playground
    glob: \\.git$
    show-hidden: true
    show-ignore: true
    xargs: dirname
  - bindkey: su # udemy
    dir: $HOME/src/udemy
    depth: 4
    glob: \\.git$
    show-hidden: true
    show-ignore: true
    xargs: dirname
