# set up the fzf directory switcher
# the fzf preview window previews the directory/file contents
# the depth of the directory preview can be configured with the depth key
# TODO: add namespaces, don't restrict to just ud
keymaps:
  # XDG_CONFIG DIRS - Top Row
  - [f, $HOME/dotfiles/bin]
  - [g, $XDG_DATA_HOME, 4]
  - [c, $XDG_CONFIG_HOME, 5]
  - [r, $XDG_CACHE_HOME]
  - [l, $HOME/dotfiles/lib, 5]
  - [xs, $XDG_STATE_HOME, 5]
  # Home Row
  - [d, $HOME/Documents, 2]
  - [h, $HOME/src/me, 4, \\.git$, true, true, dirname | xargs dirname] # this yml file is converted to json. a backslash is an escape character in json. we need to escape the backslash. we want to pass \.git$ as the regex filter to fd
  - [t, $HOME/src/playground, 5, \\.git$, true, true, dirname | xargs dirname]
  - [n, $HOME/src/clones, 4, \\.git$, true, true, dirname | xargs dirname]
  - [s, $HOME/src]
  # Bottom row
  - [b, $HOME/Documents/notes]
  - [m, $HOME/src/me/wiki/projects/ou]
  - [w, $HOME/src/me/wiki, 5]
  - [v, $HOME/Documents/candy/wiki, 5]
  - [z, $HOME/dotfiles, 4]

  - [p, /tmp]
  - [tl, $HOME/Downloads]

  - [cn, $XDG_CONFIG_HOME/nvim, 5]
  - [ck, $XDG_CONFIG_HOME/kitty]
  - [ca, $XDG_CONFIG_HOME/zsh/aliases, 5]

  # LIB
  - [lf, $HOME/.local/lib/zsh-functions]

  # CLONES
  - [nk, $HOME/src/clones/python/kitty]

  # SRC
  - [s., $HOME/src/candy/main/referralcandy-main, 5]
  - ["s,", $HOME/src/candy-main/referralcandy-main]
  - [sc, $HOME/src/candy, 5, \\.git$, true, true, dirname | xargs dirname]
  - [sh, $HOME/src/candy/main/referralcandy-main/packages/daemons]
  - [sd, $HOME/src/candy/new/devops]
  - [sdb, $HOME/src/candy/datagrip/candy]
  - [so, $HOME/src/candy/old]
  - [soc, $HOME/src/candy/old/composer]
  - [sp, $HOME/src/candy/old/pentel]
  - [sw, $HOME/src/candy/old/webapp/]
  - [st, $HOME/src/candy/old/candymold/tools]

  - [su, $HOME/src/udemy, 4, \\.git$, true, true, dirname | xargs dirname]

  - [hc, $HOME/src/me/zsh/candy]
  - [ht, $HOME/src/me/zsh/candy/klaviyo]
  - [hn, $HOME/src/me/zsh/candy/shopify]
