#!bin/zsh

function dcin(){
  # docker container inspect
  while getopts 'v' opt; do
    case "$opt" in
      v) verbose=true;;
    esac
  done
  shift $(($OPTIND - 1))

  local result=$(docker container inspect $@)
  local jqQuery='include "docker/dcin"; dcin'

  if [ $verbose ]; then
    jq --raw-output "." <<< "$result"
  else
    jq --raw-output -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< $result
  fi
}
