#!bin/zsh

function dcl(){
  # docker container ls
  # dcl -a 
  # dcl -p - plain - show original docker container ls command
  # dcl -f - exclude candy containers

  local all format formatArg filter excludeCandy debug
  while getopts 'apf' opt; do
    case "$opt" in
      a) all="-a";;
      p) plain=true;;
      f) filter=true;;
    esac
  done
  shift $(($OPTIND - 1))

if ! [ $plain ]; then
  local result=$(docker container ls $all --format="{{json .}}")

  if [ -n "$filter" ]; then
    excludeCandy='select(.Names | contains("composer") | not) '
  else
    excludeCandy="."
  fi

  local jqQuery=$(cat <<-EOF
  include "docker/dcl";
    dcl
EOF
)
  jq --raw-output --slurp -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< $result
else
  docker container ls $all
fi
}
