#!bin/zsh

function dcl(){
  # docker container ls
  # dcl -a 
  # dcl -t - show original docker container ls command
  # dcl -f - exclude candy containers

  local all format="prettyTable" formatArg filter excludeCandy debug
  while getopts 'atfd' opt; do
    case "$opt" in
      a) all="-a";;
      t) format="table";;
      f) filter=true;;
      d) debug=true;;
    esac
  done
  shift $(($OPTIND - 1))

  if [ "$format" = "table" ]; then
    formatArg="."
  else
    formatArg='--format="{{json .}}"'
  fi

  # local result=$(docker container ls $all --format="{{json .}}")
if [ "$format" = "prettyTable" ]; then
  local result=$(eval docker container ls $all $formatArg)

  if [ -n "$filter" ]; then
    excludeCandy='select(.Names | contains("composer") | not) '
  else
    excludeCandy="."
  fi

    local jqQuery=$(cat <<-EOF
   include "pad";
   include "colour";
   include "docker";
   . |
   $excludeCandy |
   "\(.ID[0:5] | __(.)) \(.Names[0:20] | rp(20)) \(.Status | prettyStatus) \(.Ports | rp(35) | _brinkPink(.)) \(.Image[0:15] | rp(15) | _tacha(.)) \(.Command[1:11] | rp(10) | __(.)) \(.CreatedAt|pCreatedAt)"
EOF
)

  [ -n "$debug" ] && echo jqQuery:"\n"$jqQuery

  jq --raw-output -L "~/.config/jq" "$jqQuery" <<< $result
else
  docker container ls $all
fi
}
