profiles:
  - name: develop
    alias: d
    ssh:
      user: ec2-user
      host: tpd-clb-temp-12111115105520.ap-southeast-1.elb.amazonaws.com
      key: ~/certis/config/secrets/certis-tpd-pmo.pem
    databases:
      user_db:
        name: argus_users
        user: useradmin
        local_port: 1100
        host: argus-users-dev.cluster-cavqivemi9xz.ap-southeast-1.rds.amazonaws.com:3306
      auth_db:
        name: argus_auth
        user: authadmin
        local_port: 1101
        host: argus-auth-dev.cluster-cavqivemi9xz.ap-southeast-1.rds.amazonaws.com:3306
