keymaps:
  - [h, zsh]
  - [ht, zsh]
  - [t, javascript-mjs]
  - [th, javascript]
  - [n, typescript]
  - [s, python]
  - [d, lua]

languages:
  # - [language, extension, shebang]
  - [zsh, zsh, zsh]
  - [javascript-mjs, mjs, node]
  - [javascript, js, node]
  - [typescript, ts, ts-node]
  - [lua, lua, lua]
  - [python, py, python]
