#!bin/zsh

function gbdd(){
  # delete local git branches with a search string
  # EXAMPLES:
  # gbdd <search string>

  #NOTE: git branch -r --merged is with reference to the branch you are currently on!
  #example: gbdd sprint-13
  #might need to run git fetch --prune to clean up remote before running this command

  local force=""
  while getopts 'x' opt; do
    case "$opt" in
      x) excludeMyBranches=true;;
    esac
  done
  shift $(($OPTIND - 1))

  # default rg search to everything (.)
  local search=${1-.}

  local exclude=()
  exclude+=("-e=\*")
  exclude+=("-e=main")
  exclude+=("-e=master")
  if [ $excludeMyBranches ]; then
    exclude+=("-e=timg/")
  fi;

  # echo $exclude

  git branch | rg -v $exclude | rg $search | xargs -P 0 -n 1 -I{} git branch -D {}
  # git branch | rg -v $exclude | rg $search
}

