#!bin/zsh

function gbll(){
  # git branch list

  # see https://git-scm.com/docs/git-for-each-ref#_field_names for the field names 
  # permitted in the git branch --format option

  local all format formatArg filter excludeCandy debug plain verbose filterOption sortOption 

  local sortBy="createdAt"
  local reverse=false 
  local imageFilter="all"

  while getopts 'apf:vs:r' opt; do
    case "$opt" in
      a) all="-a";;
      p) plain=true;;
      v) verbose=true;; # json format
      f) filterOption=$OPTARG
        case "$filterOption" in
          a) imageFilter="all";; # everyone
          m) imageFilter="me";; # me
          t) imageFilter="team";; # my team
        esac;;
      r) reverse=true;;
      s) sortOption=$OPTARG
        case "$sortOption" in
          c) sortBy="createdAt";;
          r) sortBy="repository";;
          s) sortBy="size";;
        esac;;
    esac
  done
  shift $(($OPTIND - 1))

  # author - who wrote this
  # commiter - who applied this
  local formatString=$(cat <<-EOF
		{
		         ^^^head^^^: ^^^%(HEAD)^^^,
		      ^^^refName^^^: ^^^%(refname)^^^,
		     ^^^upstream^^^: ^^^%(upstream)^^^,
		^^^committerDate^^^: ^^^%(committerdate:iso8601)^^^,
		 ^^^commiterName^^^: ^^^%(committername)^^^,
		   ^^^authorDate^^^: ^^^%(authordate:iso8601)^^^,
		   ^^^authorName^^^: ^^^%(authorname)^^^,
		      ^^^subject^^^: ^^^%(subject)^^^,
		         ^^^body^^^: ^^^%(body)^^^
		}
EOF
)

  # cleanup - replace " with \"
  # substitute ^^^ with "
  # cleanup - replace  with <empty string>
  # cleanup - replace \n with ' '

  local result=$(git branch -a --format=$formatString |
                  sed 's/"/\\"/g' | 
                  sed 's/\^^^/"/g' | 
                  sed 's///g' | 
                  tr '\n' ' ')

  if ! [ $plain ] && ! [ $verbose ]; then
  local jqQuery=$(cat <<-EOF
  include "git/branch/gbll";
    gbll("$sortBy";$reverse;"$imageFilter")
EOF
)
    jq --raw-output --slurp -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< $result
  elif [ $verbose ]; then
    printf $result | jq .
  # else
  #   # docker image ls $all
  fi
}
