#!/bin/zsh

function gg(){
  # gg - quickly add and commit files, use the filename as the commit message
  # gg -e - allow an empty commit
  # gg -e <message> - allow an empty commit, specify message
  # gg -c - commit, specify checkpoint message 

  local allowEmpty=false
  local isCheckpoint=false
  local checkpointMessage="🚧🚧🚧 checkpoint 🚧🚧🚧"
  local message

  while getopts 'ec' opt; do
    case "$opt" in
      e) allowEmpty=true;;
      c) isCheckpoint=true;;
    esac
  done
  shift $(($OPTIND - 1))

  local message="$@"

  $isCheckpoint && message=$checkpointMessage

  git add --all # git add . only works if at root of worktree
  if [ -z "$message" ]; then
    # just get the filename from the first line and use that as the commit message
    # copy from the 4th char onwards
    filepath=$(git status --porcelain | head -n 1  | cut -c 4-)
    # message=$(git-conventional-commit-msg -f $filepath -t "feat" )
  fi

  message=${message:-$filepath}

  # $allowEmpty expands to the true command which returns 0
  if $allowEmpty; then
    message=${message:-$checkpointMessage}
    git commit --allow-empty -m $message
  else
    git commit -m $message
  fi
}
