#!bin/zsh

function smg(){
  # get secret from secretsmanager

  local verbose
  while getopts 'v' opt; do
    case "$opt" in
      v) verbose=true;;
    esac
  done
  shift $(($OPTIND - 1))


  jq --raw-output -L "~/.config/jq" "$jqQuery" <<< $result

  local arn=$(sml | fzf | choose -1)

  if [ -n "$arn" ]; then 
    local result=$(aws secretsmanager get-secret-value --secret-id $arn)

    local jqQuery=$(cat <<-EOF
   include "pad";
   include "colour";
   def printSecret:
     "\(.key|lp(35)|_y(.)) \(.value | _g(.))";
     .SecretString | fromjson | to_entries | sort_by(.key) |
     map(printSecret)[]
EOF
)

    if [ -n "$verbose" ]; then
      jq --raw-output -L "~/.config/jq" "." <<< $result
    else
      jq --raw-output -L "~/.config/jq" "$jqQuery" <<< $result
    fi
  fi
}
