#!bin/zsh

function sml(){
  # list secrets
  local result=$(aws secretsmanager list-secrets)

  local jqQuery=$(cat <<-EOF
   include "pad";
   include "colour";
   include "aws-sml.data";
   include "sort";
     .SecretList |
     addSortKey("Name";_sortKeys) | sort_by(.sortKey,.Name)[] |
     "\(.Name | lp(50)) \(.Description // "" | _purple(.)) \(.ARN | _orange(.))"
EOF
)
  jq --raw-output -L "~/.config/jq" "$jqQuery" <<< $result
}
