#!bin/zsh

# search for tags
_gt() {
  is_in_git_repo || return
  git tag --sort -version:refname |
    fzf-down --multi --preview-window right:70% \
    --preview 'git show --color=always {}'
}

fzf-gt-widget(){
 local result=$(_gt | join-lines)
 zle reset-prompt
 LBUFFER+=$result
}

# after the function has been autoloaded, call the function to run it
fzf-gt-widget
