#!bin/zsh

# search for files
_gf() {
  #if not in git repo, return
  is_in_git_repo || return
  git -c color.status=always status --short |
    fzf-down -m --ansi --nth 2..,.. \
    --preview '(git diff --color=always -- {-1} | sed 1,4d; cat {-1})' |
    cut -c4- | sed 's/.* -> //'
  }

fzf-gf-widget(){
 local result=$(_gf | join-lines)
 zle reset-prompt
 LBUFFER+=$result
}

# after the function has been autoloaded, call the function to run it
fzf-gf-widget
