#!bin/zsh

function fzf-docker-container-widget() {
  # show docker containers
  # on large monitors, show side by side
  # on laptop screen, show top-bottom
  # revers-list shows prompt in center with search results on top and preview at bottom

  local fzfOut
  fzfOut=$(dcla | fzf \
    --preview-window 'right,noborder,50%,<75(bottom)' \
    --layout "reverse-list" \
    --header="⌃T ⌃V" \
    --height ~95% \
    --preview 'dcin {2}' \
    --expect 'ctrl-t,ctrl-v'
  )

  local key=$(head -1 <<< "$fzfOut")
  local selections=$(tail -n +2 <<< "$fzfOut") # get all lines after the first line
  local selection1=$(head -1 <<< "$selections")

  local selectedId=$(gawk '{print $2}' <<< "$selection1")

  if [ $selectedId ]; then
    if [ "$key" = ctrl-t ]; then
      dcin $selectedId
    elif [ "$key" = ctrl-v ]; then
      dcin -v $selectedId
    else
      local selectedIds=$(echo $selections | choose 1 | join-lines)
      LBUFFER+=$selectedIds
    fi
  fi
  zle reset-prompt
}
