-- local map = vim.api.nvim_set_keymap
-- default_options = { noremap = true, silent = true }
-- expr_options = { noremap = true, expr = true, silent = true }
--
-- map('n', '<S-C-A-u>', ':UndotreeToggle<CR>', default_options) -- undotree
