# zprofile is sourced at login
# does not affect scripts eg in ~/.local/bin
# use this file for commands and variables that don't need to be updated frequently
# run exec zsh --login to apply any configuration updates by running a login shell

# export homebrew variables
eval "$(/opt/homebrew/bin/brew shellenv)"

# https://github.com/pyenv/pyenv
# eval "$(pyenv init --path)" -- this expands to the below export PATH
export PATH="/Users/tim/.local/share/pyenv/shims:${PATH}" 

# . "/Users/tim/.local/share/cargo/env"
