#XDG setup
# base
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME=$HOME/.cache # analogous to /var/cache
export XDG_DATA_HOME=$HOME/.local/share # data that doesn't need to be modified
export XDG_STATE_HOME=$HOME/.local/state #eg logs, history. data persists btw restarts
# user
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_DOCUMENTS_DIR="$HOME/docs"
# export XDG_MUSIC_DIR="$HOME/Music"
# export XDG_PICTURES_DIR="$HOME/Pictures"
# export XDG_VIDEOS_DIR="$HOME/Videos"
export DOTFILES="$HOME/.dotfiles"

export EDITOR=nvim

# source every file (include subdirs) in .zsh
# if my libs refer to aliases, they will fail, since they are not defined?
# sequence -
# if my libs refer to functions that have not yet been defined, they will fail ?

# the join-lines function in git.zsh is used by my widgets and must be sourced here
source ~/.local/lib/zsh/fzf/git.zsh #the join-lines function is used by my widget
# the display function for my abs and home function widgets must be sourced here
source ~/.local/lib/zsh/fzf/home_fns.zsh

# SECRETS - do not store secrets in git
source ~/.dotfiles/.env

export MOBILE_CENTER_CURRENT_APP=***REMOVED***

#XDG - store your config and data somewhere tidy
_Z_DATA=$XDG_DATA_HOME/z/z # z stores its dir frecency list here
export PARALLEL_HOME=$XDG_CONFIG_HOME/parallel
export NVM_DIR=$XDG_DATA_HOME/nvm
export REDISCLI_HISTFILE=$XDG_DATA_HOME/redis/rediscli_history
export REDISCLI_RCFILE=$XDG_CONFIG_HOME/redis/redisclirc
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export NODE_REPL_HISTORY=$XDG_DATA_HOME/node_repl_history
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker #not working?
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials # vs AWS_CREDENTIALS?
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
# if enabled, web identity token breaks aws sb profile?
# export AWS_WEB_IDENTITY_TOKEN_FILE="$XDG_DATA_HOME/aws/token" 
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export TEALDEER_CONFIG_DIR=~/.config/tealdeer # https://dbrgn.github.io/tealdeer/config.html
export TEALDEER_CACHE_DIR=~/.cache/tealdeer
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
export FVM_HOME=$XDG_DATA_HOME/fvm
export PUB_CACHE=$XDG_CACHE_HOME/pub-cache # for flutter/dart
# export ANDROID_SDK_HOME=$XDG_DATA_HOME/android/.android # adb key
# export ANDROID_PREFS_ROOT=$XDG_DATA_HOME/android/.android # adb key
