#XDG setup
# base
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME=$HOME/.cache # analogous to /var/cache
export XDG_DATA_HOME=$HOME/.local/share # data that doesn't need to be modified, eg font files. write once.
export XDG_STATE_HOME=$HOME/.local/state #eg logs, history. data persists btw restarts
# user
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_DOCUMENTS_DIR="$HOME/docs"
# export XDG_MUSIC_DIR="$HOME/Music"
# export XDG_PICTURES_DIR="$HOME/Pictures"
# export XDG_VIDEOS_DIR="$HOME/Videos"
export DOTFILES="$HOME/.dotfiles"

export EDITOR=nvim

# if my libs refer to undefined aliases or funcs, they will fail. This seems to
# have been solved by function autoloading.

# SECRETS - do not store secrets in git
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"

#XDG - store your config and data somewhere tidy
export GNUPGHOME="$XDG_DATA_HOME"/gnupg

export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials # vs AWS_CREDENTIALS?
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config

export NVM_DIR=$XDG_DATA_HOME/nvm
export NODE_REPL_HISTORY=$XDG_DATA_HOME/node_repl_history
export DOCKER_CONFIG=$XDG_CONFIG_HOME/docker #not working?
export GEM_HOME=$XDG_DATA_HOME/gem # rbenv does not work if GEM_HOME is set?
export GEM_SPEC_CACHE=$XDG_CACHE_HOME/gem
export RBENV_ROOT=$XDG_DATA_HOME/rbenv
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

export MYSQL_HISTFILE=$XDG_DATA_HOME/mysql_history
export PARALLEL_HOME=$XDG_CONFIG_HOME/parallel
export REDISCLI_HISTFILE=$XDG_DATA_HOME/redis/rediscli_history
export REDISCLI_RCFILE=$XDG_CONFIG_HOME/redis/redisclirc
# export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
export TEALDEER_CONFIG_DIR=~/.config/tealdeer # https://dbrgn.github.io/tealdeer/config.html
export TEALDEER_CACHE_DIR=~/.cache/tealdeer
# alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

_Z_DATA=$XDG_DATA_HOME/z/z # z stores its dir frecency list here
