# zmodload zsh/zprof # turn this on to profile zshrc (with zprof below)
export KEYTIMEOUT=1 # Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export EDITOR='nvim'

export HISTFILE="$XDG_STATE_HOME"/zsh/history # overrid HISTFILE setting in /etc/zshenv
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt share_history # share history between terminals running at the same time, adds the strange numbers to the beginning of each line in the history file
# setopt extended_history       # record timestamp of command in HISTFLE

export NVM_AUTO_USE=true # zsh-nvm plugin autoloads .nvmrc, set before the plugins array
export NVM_LAZY_LOAD=true  # zsh-nvm lazy load
ZSH_EVALCACHE_DIR=$XDG_CACHE_HOME/zsh-evalcache

bindkey -e # use emacs keymap for zsh

setopt autocd # type dir name to cd directly
autoload zmv # so i can use zmv immediately
autoload -U colors && colors # enable $fg[red] etc

# TODO: how are completions here loaded?
fpath=(/opt/homebrew/share/zsh/site-functions $fpath) # add homebrew completions to fpath

# place the homebrew binaries at the end of path, if not nvm will always point to the homebrew system node
# export PATH="/Users/tim/Library/Python/3.9/bin:$PATH"

export PATH="$PATH:/opt/homebrew/bin" # access aws_completer, etc
export PATH="$PATH:$HOME/.local/bin"
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"

# source zinit
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# NOTE: zinit install
zinit ice depth=1; zinit light romkatv/powerlevel10k

zinit for \
  OMZP::last-working-dir \
  mroth/evalcache \

# lazy load plugins
zinit lucid wait for \
  lukechilds/zsh-nvm \
  OMZP::gitignore \
  rupa/z \
  OMZP::aws/aws.plugin.zsh \
  OMZP::timer \
  marlonrichert/zsh-autocomplete \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  atinit"zicompinit; zicdreplay; nvm use default --silent; _evalcache pyenv init -; _evalcache funky --init zsh; _evalcache rbenv init -" \
      zdharma-continuum/fast-syntax-highlighting \

# zicompinint runs autoload compinit; compinit
# zicdreplay replays the captured compdefs

### NOTE: Source my config and functions
source $DOTFILES/config/secret/env

setopt EXTENDED_GLOB # use ~ to exclude patterns in file globbing
source $XDG_CONFIG_HOME/zsh/start/SOURCEME.zsh # source oh-my-zsh and other custom plugins
for f in $XDG_CONFIG_HOME/zsh/***/*.zsh~*/start/*; do # exclude start folders
  source $f 
done 
fpath=($HOME/.local/lib/zsh/***/*~*/archive*(/) $fpath) # / matches directories, exclude archive/
for func in $HOME/.local/lib/zsh/***/*~(*/archive/*|*.zsh)(.); do 
  autoload $func
done
unsetopt EXTENDED_GLOB

# set up p10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# set aws credential env vars
# asst > /dev/null
asst

# enter tmux on start up if using kitty (depends on tat script in bin folder)
if [[ $TERM = "xterm-kitty" ]] && [[ -z "$TMUX" ]]; then
  tat
fi
# zprof # turn this on to profile zsh (with zmodload zsh/zprof above)
