require('core.disable-plugins')
require('utils')
require('diagnostic')
require('plugins')
require('maps')
require('options')
-- define colorscheme here
-- the colorscheme might set highlight clear, undoing all your highlight groups?
require('core.colours')
require('core.autocmd')
require('tg.toggle-interface')
require('tg.toggle-test')
require('tg.treesitter-utils')
require('tg.telescope-multi-rg')
require('tg.test-runner')
require('tg.misc')
