require('maps.defaults')
require('maps.modifiers')
require('maps.local-leader')
require('maps.goto')

require('maps.core.panes')
require('maps.core.buffers')
require('maps.core.windows')
require('maps.core.nvim-tmux-navigation')
require('maps.core.quick-fix')

require('maps.plugins.dap')
require('maps.plugins.nvim-tree')
require('maps.plugins.undo-tree')
require('maps.plugins.trouble')
require('maps.plugins.git-signs')
require('maps.plugins.lsp')
require('maps.plugins.vim-kitty-navigator')
