require('maps.defaults')
require('maps.modifiers')
require('maps.local-leader')
require('maps.goto')

require('maps.core.panes')
require('maps.core.buffers')
require('maps.core.windows')
require('maps.core.nvim-tmux-navigation')
require('maps.core.quick-fix')
