#!/bin/zsh

function boc(){
  # big commerce orders create

  local email_suffix=${1:-$RANDOM}

# https --ignore-stdin --check-status --quiet post https://api.bigcommerce.com/stores/$BG_STORE_HASH/v2/orders X-Auth-Token:$BG_ACCESS_TOKEN \
local result=$(https --ignore-stdin --check-status -p=b post https://api.bigcommerce.com/stores/$BG_STORE_HASH/v2/orders X-Auth-Token:$BG_ACCESS_TOKEN \
  "billing_address[first_name]=jane" \
  "billing_address[last_name]=doe" \
  "billing_address[street_1]=Tampines Street 123 Blk 548 #09-123" \
  "billing_address[street_2]=Fernval Dew" \
  "billing_address[city]=Singapore" \
  "billing_address[state]=Tampines" \
  "billing_address[zip]=123789" \
  "billing_address[country]=Singapore" \
  "billing_address[country_iso2]=SG" \
  "billing_address[phone]=87844444444" \
  "billing_address[email]=timothyg+${email_suffix}@anafore.com" \
  "products[0][name]=tim" \
  "products[0][quantity]=1" \
  "products[0][price_inc_tax]=50" \
  "products[0][price_ex_tax]=49" \
  "status_id=11" \
  "ip_address=12.345.678.910")

  local orderId=$(jq '.id' <<< "$result")
  local email=$(jq '.billing_address.email' <<< "$result")

  echo orderId $orderId created for $email
}
