#!bin/zsh

function lg(){
  # change directory to the repo selected in lazygit on exit
  # useful for git worktrees
  # https://github.com/jesseduffield/lazygit#changing-directory-on-exit

  export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir

  lazygit "$@"

  if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
          cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
          rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
  fi
}
