#!/bin/zsh

function _aws-unset-key-env(){
  # unset env vars
  unset AWS_DEFAULT_PROFILE
  unset AWS_PROFILE
  unset AWS_EB_PROFILE

  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
  unset AWS_SESSION_TOKEN
}
