#!bin/zsh

function as(){
  # switch aws profiles
  # as t - use tim profile
  # as c - use candy profile

  local profile=$1

  _aws-unset-key-env # unset all the variables set by asst or as

  case $profile in
    t)
      _aws-set-profile-env tim
      ;;
    c)
      # cl does not work if i set a profile ??
      # _aws-set-profile-env default
      asst
      ;;
    *)
      echo "${fg[red]} no profile found ${reset_color}"
  esac
}
