#!/bin/zsh

function acl(){
  # aws cloudformation list-stacks
  # aws lists stacks that have been deleted for up to 90 days
  # -v
  # -a - show all, else exclude deleted

  local verbose filter all
  while getopts 'va' opt; do
    case "$opt" in
      v) verbose=true;;
      a) all=true;;
    esac
  done
  shift $(($OPTIND - 1))

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html

  local result=$(aws cloudformation list-stacks --stack-status-filter $filter)

  local jqQuery=$(cat <<-EOF
    include "aws/cf/acl";
    acl("$all")
EOF
)

  if [ $verbose ]; then
    jq --raw-output "." <<< "$result"
  else
    jq --raw-output -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< "$result"
  fi

}
