#!/bin/zsh

function afl(){
  # aws cloudformation list-stacks sort by update time descending
  # aws lists stacks that have been deleted for up to 90 days
  # -v
  # -a - show all, else exclude deleted
  # -s - sort by name
  # -n - limit
  # -u - region us-east-1

  local verbose filter all sortByName limit region
  while getopts 'vasn:u' opt; do
    case "$opt" in
      v) verbose=true;;
      a) all=true;;
      s) sortByName=true;;
      n) limit=$OPTARG;;
      u) region=us-east-1
    esac
  done
  shift $(($OPTIND - 1))

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html

  region=${region:-ap-southeast-1}
  echo region is $region

  local result=$(aws cloudformation list-stacks --stack-status-filter $filter --region $region)
  local limit=${limit:-40}

  local sortOpt
  if [ $sortByName ]; then
    sortOpt="name"
  else
    sortOpt="date"
  fi
  echo sortOpt is $sortOpt

  local jqQuery=$(cat <<-EOF
    include "aws/cf/afl";
    afl("$all"; "$sortOpt")
EOF
)

  if [ $verbose ]; then
    jq --raw-output "." <<< "$result" | head -n $limit
  else
    jq --raw-output -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< "$result" | head -n $limit
  fi

}
