#!bin/zsh

function _apa(){
  # action-executions
  # aws codepipeline list-action-executions
  # _apa <pipelineName> <id>

  local pipelineName=$1
  local id=$2

  local result=$(aws codepipeline list-action-executions --pipeline-name $pipelineName --filter pipelineExecutionId=$id)

  jq '.' <<< "$result"
}
