#!bin/zsh

function _ape(){
  # list pipeline executions
  # aws codepipeline list-action-executions
  # _ape <pipelineName> <maxItems>

  local pipelineName=$1
  local n=$2

  local result=$(aws codepipeline list-pipeline-executions --pipeline-name $pipelineName --max-items $n)

  jq '.' <<< "$result"
}
