#!bin/zsh

function apa(){
  # action-executions
  # aws codepipeline list-action-executions

  local verbose summary=false oneline=false
  while getopts 'vso' opt; do
    case "$opt" in
      v) verbose=true;;
      s) summary=true;;
      o) oneline=true;;
    esac
  done
  shift $(($OPTIND - 1))

  local id=$1

  local statusResult=$(ape -v)
  local jqQueryStatus=$(cat <<-EOF
    include "pad";
    include "colour";
    include  "date";
    .pipelineExecutionSummaries
    | map(select(.pipelineExecutionId == "$id"))
    | .[]
    | .status
EOF
)

  local pipelineStatus=$(jq --raw-output -L "~/.config/jq" "$jqQueryStatus" <<< $statusResult)
  local cacheKey="aws/apa/$id"
  # echo cacheKey is $cacheKey
  rcache "$cacheKey.604800" _apa $id
  local result=$(rcg "aws/apa/$id")

  local jqQuery=$(cat <<-EOF
    include "aws/codepipeline/apa/_entry";
    _entry("$oneline";"$pipelineStatus";"$summary")
EOF
)

  if [ $verbose ]; then
    jq --raw-output "." <<< "$result"
  else
    jq --raw-output -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< "$result"
  fi
}
