#!/bin/zsh
function ebd(){
  # disable event bridge rules
  # e.g. acdd "my-app" - dry run the delete
  # e.g. acdd "my-app" "force" - actually delete the task definition
  local search=$1
  local force=$2

  results=$(aws events list-rules| jq --raw-output '.Rules[] | .Name' | rg "$search" )

  while read -r line; do
    echo "$line"
  done <<< "$results"

  if [ -n "$force" ]; then
    while read -r line; do
      echo "$fg[yellow]Disabling${reset_color} $line"
      aws events disable-rule --name $line
    done <<< "$results"
  fi
}
