#!/bin/zsh
function ebd(){
  # disable event bridge rules
  # e.g. ebd "<search term>" - dry run the disable rule
  # e.g. ebd "<search term>" "force" - actually disable the rule
  local search=$1
  local force=$2

  results=$(aws events list-rules| jq --raw-output '.Rules[] | .Name' | rg "$search" )

  while read -r line; do
    echo "$line"
  done <<< "$results"

  if [ -n "$force" ]; then
    while read -r line; do
      echo "$fg[yellow]Disabling${reset_color} $line"
      aws events disable-rule --name $line
    done <<< "$results"
  fi
}
