#!/bin/zsh

function seu(){
  # setupper - set up projects

  local verbose quiet
  while getopts 'vq' opt; do
    case "$opt" in
      v) verbose=true;;
      q) quiet=true;;
    esac
  done
  shift $(($OPTIND - 1))

  local prettierYml=$DOTFILES/templates/eslint/.eslintrc.yml
  local eslintYml=$DOTFILES/templates/prettier/.prettierrc.yml

  echo copying $prettierYml to here
  cp $prettierYml .

  echo copying $eslintYml to here
  cp $eslintYml .

}
