#!bin/zsh

function ctime() {
  # convert epoch time in ms to date
  ms=${1: -3} #get last 3 digits (milliseconds)
  y=${1%???} #another way to remove last 3 chars
  ts=${1:0:-3} #remove last 3 chars to get epoch ts without ms

  strftime "%a %b %e %H:%M:%S.$ms %Y" $ts
}
