#!/bin/zsh

# no longer in use
function backward-kill-dir () {
# see pattern replacement in https://zsh.sourceforge.io/Guide/zshguide05.html
    # local WORDCHARS=${WORDCHARS/=\/}
    # // - globally replace
    # [<chars to remove>]
    # escape special chars like / and {}
    local WORDCHARS=${WORDCHARS//[_.$=\/()\{\}]}
    zle backward-kill-word
    zle -f kill  # Ensures that after repeated backward-kill-dir, Ctrl+Y will restore all of them.
}

# related info
# remove / from wordchars so that I can remove dir segments with ctrl-w
# https://unix.stackexchange.com/questions/48577/modifying-the-zsh-shell-word-split
# export WORDCHARS=$WORDCHARS:s:/:
