#!/bin/zsh

function execute-buffer-with-git-show-widget() {
  # if [[ $BUFFER != "nvim "* ]]; then
    BUFFER="gsv $BUFFER"; CURSOR+=2
    zle accept-line
  # fi
}
 execute-buffer-with-git-show-widget
