#!/bin/zsh

function execute-buffer-in-nvim-widget() {
  if [[ $BUFFER != "nvim "* ]]; then
    local buffer=$(echo $BUFFER | tr -d ' ') # strip whitespace from buffer
    local realpath=$(readlink $buffer) # readlink <file> checks if file is a symbolic link

    if [ -n "$realpath" ]; then
      BUFFER="nvim $realpath";
    else
      BUFFER="nvim $BUFFER"; # the file doesnt exist yet or is not a symbolic link
    fi
    zle end-of-line # move cursor to end of line
    zle accept-line
  fi
}
