#!/bin/zsh

function pb-backward-kill-line () {
  zle backward-kill-line
  # if CUTBUFFER contains -t eg, 
  # then -t is passed to print 
  # instead pass - to print to tell print to print $CUTBUFFER literally
  print -rn - $CUTBUFFER | pbcopy
}
