#!/bin/zsh

function pb-backward-kill-word () {
  # see pattern replacement in https://zsh.sourceforge.io/Guide/zshguide05.html
  # local WORDCHARS=${WORDCHARS/=\/}
  # // - globally replace
  # [<chars to remove>]
  # escape special chars like / and {}

  # local WORDCHARS=${WORDCHARS//[\/=_.$\{\}()]}
  zle backward-kill-word
  print -rn $CUTBUFFER | pbcopy
}

