#!/bin/zsh

function acrbgi(){
  # aws ecr batch get image
  # acrbgi <repository name> <tag>
  # acrbgi -r <repository name> -t <tag>
  # (aws ecr batch-get-image)
  # eg acrbgi daemon-v2 <tag>

  # if you provide max items, it won't get the latest image!!!

  local verbose repository tag
  while getopts 'vr:t:' opt; do
    case "$opt" in
      v) verbose=true;;
      r) repository=$OPTARG;;
      t) tag=$OPTARG;;
    esac
  done
  shift $(($OPTIND - 1))

  #TODO specify multiple images with --image-ids imageTag=abc imageTag=def

  repository=${repository:-$1}
  tag=${tag:-$2}

    local jqQuery=$(cat <<-EOF
   include "pad";
   include "colour";
   include "aws-time";
     .
EOF
)

  local result=$(aws ecr batch-get-image --repository-name $repository --image-ids imageTag=$tag)

  if [ -n "$verbose" ]; then
    jq --raw-output -L "~/.config/jq" "." <<< $result
  else
    jq --raw-output -L "~/.config/jq" "$jqQuery" <<< $result
  fi
}
