#!/bin/zsh

function acri(){
  # aws ecr images list
  # acri <repository name>
  # acri -n 40 <repository name>
  # acri -r <repository name>
  # acri -r <repository name> -s a # sort imagePushedAt ascending
  # acri -r <repository name> -s d # sort imagePushedAt descending
  # acri -r <repository name> -s p # sort lastRecordedPullTime descending
  # (aws ecr describe-images)

  # if you provide max items, it won't get the latest image!!!

  local verbose repository number _n sort
  while getopts 'vr:n:s:' opt; do
    case "$opt" in
      v) verbose=true;;
      r) repository=$OPTARG;;
      n) number=$OPTARG;;
      s) sort=$OPTARG
        case "$sort" in
          a) sort="ascending";; # imagePushedAt ascending 
          d) sort="descending";; # imagePushedAt descending
          p) sort="pulled";; # lastRecordedPullTime descending
        esac
        ;;
    esac
  done
  shift $(($OPTIND - 1))

  _n=${number:-1999}
  sort=${sort:-descending}
  repository=${repository:-$1}

  local jqQuery=$(cat <<-EOF
    include "aws/ecr/acri";
    acri("$sort";$_n)
EOF
)

  #   result=$(aws ecr describe-images --repository-name $repository --query 'reverse(sort_by(imageDetails, &(lastRecordedPullTime || ``)))')
    local result=$(aws ecr describe-images --repository-name $repository )

  if [ -n "$verbose" ]; then
    jq --raw-output -L "~/.config/jq" "." <<< $result
  else
    jq --raw-output -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< $result
  fi
}
