#!/bin/zsh

function acri(){
  # aws ecr images list
  # acri <repository name>
  # acri -n 40 <repository name>
  # acri -r <repository name>
  # (aws ecr describe-images)

  # if you provide max items, it won't get the latest image!!!

  local verbose repository number _n
  while getopts 'vr:n:' opt; do
    case "$opt" in
      v) verbose=true;;
      r) repository=$OPTARG;;
      n) number=$OPTARG;;
    esac
  done
  shift $(($OPTIND - 1))

  _n=${number:-999}
  repository=${repository:-$1}

  # TODO: sort by last pull time
    # aws ecr describe-images --repository-name ... --query 'reverse(sort_by(imageDetails, &(lastRecordedPullTime || ``)))'
    # TODO: pass n
    # TODO format date

  local jqQuery=$(cat <<-EOF
    include "aws/ecr/acri";
    acri
EOF
)

  local result=$(aws ecr describe-images --repository-name $repository )

  if [ -n "$verbose" ]; then
    jq --raw-output -L "~/.config/jq" "." <<< $result
  else
    jq --raw-output -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< $result
  fi
}
