#!/bin/zsh

function acri(){
  # aws ecr images list
  # acri <repository name>
  # acri -n 40 <repository name>
  # acri -r <repository name>
  # (aws ecr describe-images)

  # if you provide max items, it won't get the latest image!!!

  local verbose repository number _n
  while getopts 'vr:n:' opt; do
    case "$opt" in
      v) verbose=true;;
      r) repository=$OPTARG;;
      n) number=$OPTARG;;
    esac
  done
  shift $(($OPTIND - 1))

  _n=${number:-20}
  repository=${repository:-$1}

    local jqQuery=$(cat <<-EOF
   include "pad";
   include "colour";
   include "aws-time";
     .imageDetails | 
     sort_by(.imagePushedAt) | reverse | 
     .[0:$_n] |
     .[] |
     "\(.imagePushedAt ) \(.imageSizeInBytes / 1000000 | floor) MB \(.imageTags )"
EOF
)

  local result=$(aws ecr describe-images --repository-name $repository )

  if [ -n "$verbose" ]; then
    jq --raw-output -L "~/.config/jq" "." <<< $result
  else
    jq --raw-output -L "~/.config/jq" "$jqQuery" <<< $result
  fi
}
