#!/bin/zsh

function sa(){
  # sampler - open dashboard
  # sa -l - local

  while getopts 'l' opt; do
    case "$opt" in
      l) localOpt=true;;
    esac
  done
  shift $(($OPTIND - 1))

  if [ $localOpt ]; then
    sampler -c $DOTFILES/lib/zsh/candy/sampler/local.yml
  else
    sampler -c $DOTFILES/lib/zsh/candy/sampler/config.yml
  fi
}
