[general]
shell = "zsh"
# do not use a login shell, source functions in zshenv so they are available to
# viddy when viddy runs zsh non-interactively
# shell_options = "--login"

[keymap]
timemachine_go_to_past = "j"
timemachine_go_to_more_past = "h"
timemachine_go_to_future = "k"
timemachine_go_to_more_future = "t"
timemachine_go_to_now = "b"
timemachine_go_to_oldest = "d"

[color]
# background = "white" # Default value is inherit from terminal color.
