#!/bin/zsh

function dls(){
  # datadog search logs

  local verbose quiet
  while getopts 'vq' opt; do
    case "$opt" in
      v) verbose=true;;
      q) quiet=true;;
    esac
  done
  shift $(($OPTIND - 1))

  https -p=h post "https://api.datadoghq.com/api/v2/logs/events/search" \
    "DD-API-KEY":$DD_API_KEY \
    "DD-APPLICATION-KEY":$DD_APP_KEY
}
