#!bin/zsh

# calls ape
# calls _ape
# aws codepipeline lst-pipeline-executions

function _fzf-code-pipeline-widget() {
# show the action executions for a pipeline 
# show ape by default
  local id
  local PIPELINE_NAME=$1
  # id=$(ape | fzf | awk '{print $4}')
  local out=$( ape $PIPELINE_NAME | \
    fzf --ansi --multi \
    --preview-window top,noborder,7 \
    --header="⌃S ⌃L" \
    --preview 'apa -p {3} -s {5}' \
    --bind 'ctrl-/:change-preview-window(right,40%|down,60%,border-top|hidden|)' \
    --bind "alt-r:reload(rcda aws >/dev/null ; ape $PIPELINE_NAME)" \
    --expect=ctrl-s,ctrl-l
  )

  local key=$(head -1 <<< "$out")
  local targets=$(tail -n +2 <<< "$out") # get all lines after the first line
  local target1=$(head -1 <<< "$targets")

  local id=$(gawk '{print $5}' <<< "$target1")
  local pipelineName=$(gawk '{print $3}' <<< "$target1")
  if [ $id ]; then
    if [ "$key" = ctrl-s ]; then
      # apa -s $id
      # local branches=()

      while IFS= read -r execution ; do 
        # remove first 2 chars of line (contains empty space or *)
        # local branch=${gitbranchline:2}
        local id=$(gawk '{print $5}' <<< "$execution")
        local pipelineName=$(gawk '{print $3}' <<< "$execution")
        apa -p $pipelineName -s $id
        # add a newline so that zle reset-prompt doesnt swallow the last line of apa
        # apparently, zle-reset-prompt doesn't play well with multiline prompts
        # https://stackoverflow.com/questions/9212508/how-to-redraw-the-zsh-prompt-after-widget-action
        echo
      done <<< "$targets"

      # for branch in $branches; do
      #   git branch -D $branch
      # done
      zle reset-prompt
      return
    elif [ "$key" = ctrl-l ]; then
      while IFS= read -r execution ; do 
        # remove first 2 chars of line (contains empty space or *)
        # local branch=${gitbranchline:2}
        local id=$(gawk '{print $5}' <<< "$execution")
        local pipelineName=$(gawk '{print $3}' <<< "$execution")
        apa -p $pipelineName -o $id
        # add a newline so that zle reset-prompt doesnt swallow the last line of apa
        # apparently, zle-reset-prompt doesn't play well with multiline prompts
        # https://stackoverflow.com/questions/9212508/how-to-redraw-the-zsh-prompt-after-widget-action
        echo
      done <<< "$targets"
    else
      # show detail view of pipeline
      apa -p $pipelineName $id
      # add a newline so that zle reset-prompt doesnt swallow the last line of apa
      # apparently, zle-reset-prompt doesn't play well with multiline prompts
      # https://stackoverflow.com/questions/9212508/how-to-redraw-the-zsh-prompt-after-widget-action
      echo
    fi
  fi

  zle reset-prompt
  return
}
