#!bin/zsh

function fzf-code-pipeline-widget() {
# show the action executions for a pipeline 
  local id
  # id=$(ape | fzf | awk '{print $4}')
  local out=$( ape | \
    fzf --ansi --multi --tac --preview-window right:wrap \
    --preview 'apa -s {4}' \
    --bind 'ctrl-/:change-preview-window(right,40%|right,80%|down,90%,border-top|hidden|)' \
    --expect=ctrl-d,ctrl-s
  )

  local key=$(head -1 <<< "$out")
  local targets=$(tail -n +2 <<< "$out") # get all lines after the first line
  local target1=$(head -1 <<< "$targets")

  local id=$(gawk '{print $4}' <<< "$target1")

  if [ $id ]; then
    if [ "$key" = ctrl-s ]; then
      # apa -s $id
      # local branches=()

      while IFS= read -r execution ; do 
        # remove first 2 chars of line (contains empty space or *)
        # local branch=${gitbranchline:2}
        local id=$(gawk '{print $4}' <<< "$execution")
        apa -s $id
      done <<< "$targets"

      # for branch in $branches; do
      #   git branch -D $branch
      # done
      zle reset-prompt
      return
    elif [ "$key" = ctrl-d ]; then
      apa $id
    else
      apa $id
    fi
  fi

  zle reset-prompt
  return
}
