#XDG setup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME=$HOME/.cache # analogous to /var/cache
export XDG_DATA_HOME=$HOME/.local/share # data that doesn't need to be modified
export XDG_STATE_HOME=$HOME/.local/state #eg logs, history. data persists btw restarts

export EDITOR=nvim

# source every file (include subdirs) in .zsh
for f in ~/.local/lib/zsh/***/*; do [[ -f $f ]] && . $f; done
for f in ~/.local/lib/abs/***/*.zsh; do [[ -f $f ]] && . $f; done

# SECRETS
export GMAIL_TIMTESTALLTHETHINGS_PASSWORD=***REMOVED*** # export email pw for mutt
export APPCENTER_ACCESS_TOKEN=***REMOVED***
NETLIFY_AUTH_TOKEN=***REMOVED***
GITHUB_TOKEN=***REMOVED***
GITLAB_PRIVATE_TOKEN=***REMOVED*** # use this for my gitlab
NAS_SSH_PASSWORD=***REMOVED*** # use this to shut down nas via ssh


export MOBILE_CENTER_CURRENT_APP=***REMOVED***

#XDG - store your config and data somewhere tidy
_Z_DATA=$XDG_DATA_HOME/z/z # z stores its dir frecency list here
export PARALLEL_HOME=$XDG_CONFIG_HOME/parallel
export NVM_DIR=$XDG_DATA_HOME/nvm
export REDISCLI_HISTFILE=$XDG_DATA_HOME/redis/rediscli_history
export REDISCLI_RCFILE=$XDG_CONFIG_HOME/redis/redisclirc
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export NODE_REPL_HISTORY=$XDG_DATA_HOME/node_repl_history
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker #not working?
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials # vs AWS_CREDENTIALS?
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
export AWS_WEB_IDENTITY_TOKEN_FILE="$XDG_DATA_HOME/aws/token"
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export TEALDEER_CONFIG_DIR=~/.config/tealdeer # https://dbrgn.github.io/tealdeer/config.html
export TEALDEER_CACHE_DIR=~/.cache/tealdeer
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
export FVM_HOME=$XDG_DATA_HOME/fvm
