#!/bin/zsh

function fzf-my-history-widget() {
  local selected num
  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
  # sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd)
  # sub(/^[ \t]*[0-9]+\**[ \t]+[0-9-]{10} [0-9:]{5}[ \t]*/, "", cmd)
  #
  # selected=( $(fc -rl 1 | awk '{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd); if (!seen[cmd]++) print $0 }' |
  # FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} ${FZF_DEFAULT_OPTS-} -n2..,.. --scheme=history --bind=ctrl-r:toggle-sort,ctrl-z:ignore ${FZF_CTRL_R_OPTS-} --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )

  local filterUniqueCommandsWithIsoDate='{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+.{16}[ \t]*/, "", cmd); if (!seen[cmd]++) print $0 }'
  local filterUniqueCommands='{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd); if (!seen[cmd]++) print $0 }'

  # this is too slow
  # selected=$(fc -rli 1 | awk $filterUniqueCommandsWithIsoDate \
  # selected=$(fc -rl 1 | awk $filterUniqueCommands \
  #         | fzf
  #         ) 
  selected=( $(fc -rl 1 | awk '{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd); if (!seen[cmd]++) print $0 }' |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} ${FZF_DEFAULT_OPTS-} -n2..,.. --scheme=history --bind=ctrl-r:toggle-sort,ctrl-z:ignore ${FZF_CTRL_R_OPTS-} --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )

  # echo selected is $selected
  local ret=$?
  if [ -n "$selected" ]; then
    num=$selected[1]
    # echo num is $num
    if [ -n "$num" ]; then
      zle vi-fetch-history -n $num
    fi
  fi
  zle reset-prompt
  return $ret
}
