#!/bin/zsh

function fzf-t-widget() {

  local readonly basename="$WIDGET"

  local FD_COMMAND="fd $FD_OPTIONS"
  local FD_OPTIONS="--color always --follow --hidden"
  local FILE_PREVIEW="[[ \$(file --mime {}) =~ inode/directory ]] && exa --tree --long --icons --git --color always --octal-permissions --sort created --reverse {} || (bat --style=numbers,header-filename --color=always {} || cat {}) 2> /dev/null | head -300"
  local BLAME_PREVIEW="git blame {} | delta --hyperlinks"

  if blame_state="$(mktemp "/tmp/${basename}".XXXXXX)"; then
    printf 'blame' > "${blame_state}"
  fi

  local out=$(fd ${=FD_OPTIONS} | 
    FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS" fzf --ansi \
        --preview "$FILE_PREVIEW" \
        --header="⌃A ⌃O | ⌃G ⌃C ⌃R _ ⌃H ⌃T | ⌥G ⌥R" \
        --header-first \
        --preview="fzf-fd-preview {}" \
        --preview-window='right:nowrap,noborder,75%' \
        \
        --bind "ctrl-g:reload(fd $FD_OPTIONS --type d)+change-prompt(dir> )" \
        --bind "ctrl-c:reload(fd $FD_OPTIONS_NO_IGNORE)+change-prompt(no-ignore> )" \
        --bind "ctrl-r:reload(fd $FD_OPTIONS --type f)+change-prompt(file> )" \
        \
        --bind "ctrl-h:reload(fd $FD_OPTIONS --type f --exec-batch ls -lt | choose 8)+change-prompt(files-sorted> )" \
        --bind "ctrl-t:reload(fd $FD_OPTIONS)+change-prompt(> )" \
        \
        --bind "ctrl-o:change-preview(
          if grep -q 'blame' ${blame_state}; then 
            git blame {} | delta --hyperlinks
          else 
            fzf-fd-preview {}
          fi;
          _fzf-docker-image-widget-toggle $blame_state blame;
          )+refresh-preview" \
        \
        --bind "alt-g:reload(fd $FD_OPTIONS --type f --max-depth 1 )+change-prompt(depth:1> )" \
        --bind "alt-r:reload(fd $FD_OPTIONS --type f --max-depth 2 )+change-prompt(depth:2> )" \
        --expect=ctrl-b
  )
  rm -f "${blame_state}" &> /dev/null

  local key=$(head -1 <<< "$out")
  local targets=$(tail -n +2 <<< "$out") # get all lines after the first line
  local target1=$(head -1 <<< "$targets")

  local id=$(gawk '{print $1}' <<< "$target1")

  if [ $id ]; then
    if [ "$key" = ctrl-b ]; then
      git blame $target1 | delta --hyperlinks
    else
      local selectedIds=$(echo $targets | join-lines)
      LBUFFER+=$selectedIds
    fi;
  fi

  zle reset-prompt
  return
}
