#!bin/zsh
# search for filename and file contents
# edits the file after picking the fzf entry

function fzf-filename-and-content(){
  # et <dir> searches for the filename and its contents in <dir>
  # <dir> defaults to cwd if none provided

  local dir=$1

  local fzfEntry=$(rg --follow --line-number --with-filename . $dir --color=always --field-match-separator ' '\
    | fzf --preview "bat --style=numbers,header-filename --color=always {1} --highlight-line {2}" \
    --preview-window "right,noborder,~1,+{2}+1/2,<80(up)"
  )

  if [ -n "$fzfEntry" ]; then
    local file lineNumber
    read -r file lineNumber _ <<< $fzfEntry
    nvim $file +$lineNumber -c 'normal! zz'
  fi
}
