#!/bin/zsh

function cr(){
  # list cloudfront distributions
  local verbose
  while getopts 'v' opt; do
    case "$opt" in
      v) verbose=true;;
    esac
  done
  shift $(($OPTIND - 1))

  # local result=$(aws cloudfront list-distributions)
  local result=$(CT)

  local jqQuery=$(cat <<-EOF
    include "aws/cloudfront/cr";
    cr
EOF
)

  if [ $verbose ]; then
    jq --raw-output "." <<< "$result"
  else
    jq --raw-output -L "~/.config/jq" -L "~/.local/lib/jq" "$jqQuery" <<< "$result"
  fi
}
