# set up the fzf directory switcher 
# specify the bindkey for the ud function
# ud is a fzf directory switcher
# the fzf preview window previews the directory/file contents
# the depth of the directory preview can be configured with the options key
# TODO: add namespaces, don't restrict to just ud
# TODO: add ignore glob options (use exa -i)
# TODO: cache edited files with nvim

keymaps:
  # XDG folders
  - bindkey: c #udc opens fzf and lists its directory contents
    dir: $XDG_CONFIG_HOME
    options: 3
  - bindkey: a
    dir: $XDG_CACHE_HOME
  - bindkey: t
    dir: $XDG_DATA_HOME
    options: 4
  - bindkey: s
    dir: $XDG_STATE_HOME
    options: 2
  - bindkey: b
    dir: $HOME/.local/bin
  - bindkey: l
    dir: $HOME/.local/lib
    options: 3 # specify how deep the directory preview should be

  # my dotfiles
  - bindkey: z
    dir: $HOME/.dotfiles
    options: 4

  # other folders
  - bindkey: d
    dir: $HOME/Downloads

  # tmp folders
  - bindkey: p # tmP
    dir: /tmp
  - bindkey: pc
    dir: /tmp/certify-verifysync
  - bindkey: pcr
    dir: /tmp/certify-verifysync/report

  - bindkey: scu # State Certify Users - sap s3 uploads
    dir: $_CERTIFY_S3_BUCKET_SAP_SYNC_LOCAL_FOLDER

  # read the src
  - bindkey: oc
    dir: $HOME/src/certis
    options: 3 # specify how deep the directory preview should be
  - bindkey: om
    dir: $HOME/src/me
    options: 3
  - bindkey: ob
    dir: $HOME/src/books
  - bindkey: oo
    dir: $HOME/src/open

  # my projects
  - bindkey: w # my website
    dir: $HOME/src/me/website/docs
    options: 5 # specify how deep the directory preview should be

  # (ノ ゜Д゜)ノ ︵ ┻━┻ flipping playground
  - bindkey: dp # my website
    dir: $HOME/dev/playground
    options: 3 # specify how deep the directory preview should be
