#!/bin/zsh

function nt(){
  # nt <dir> <cmd>
  # nt <cmd> - defaults dir to my dotfiles
  # use entr to run <cmd> when files in <dir> change

  # https://stackoverflow.com/questions/9057387/process-all-arguments-except-the-first-one-in-a-bash-script
  local directories=$1
  local cmd="${@:2}"

  # -cc clears the screen and scrollback as well
  # prefer entr zsh -c to entr -s
  # entr -s prints the exit code which is noisy
  # no ignore - i want to trigger for example the scratchz jq file
  if [[ $directories == /Users/tim/src/candy/main/referralcandy-main/* ]]; then
    fd --no-ignore --exclude '.git' --exclude 'node_modules' . ${=directories} | entr -cc npx ava --fail-fast $cmd
  else
    fd --no-ignore --exclude '.git' --exclude 'node_modules' . ${=directories} | entr -cc zsh -c $cmd
  fi
}
