#!/bin/zsh

function nt(){
  # nt [dir] <cmd>
  # use entr to run <cmd> when files in <dir> change
  # if dir not supplied, default to ~/dotfiles
  local rootDir=~/dotfiles
  while getopts 'd:' opt; do
    case "$opt" in
      d) rootDir=$OPTARG;;
    esac
  done
  shift $(($OPTIND - 1))

  local cmd="$@"

  # -cc clears the screen and scrollback as well
  # prefer entr zsh -c to entr -s
  # entr -s prints the exit code which is noisy
  fd . $rootDir | entr -cc zsh -c $cmd
}
