#!/bin/zsh

function nt(){
  # nt [dir] <cmd>
  # use entr to run <cmd> when files in <dir> change
  # if dir not supplied, default to ~/dotfiles

  local rootDir cmd

  if [ $# -eq 1 ]; then
    rootDir=~/dotfiles
    cmd=$1
  else
    rootDir=$1
    cmd=$2
  fi

  # -cc clears the screen and scrollback as well
  # prefer entr zsh -c to entr -s
  # entr -s prints the exit code which is noisy
  fd . $rootDir | entr -cc zsh -c $cmd
}
