#!bin/zsh

function hh(){
  # https://unix.stackexchange.com/questions/147563/how-do-i-repeat-the-last-command-without-using-the-arrow-keys
  # repeat the last command
  # oops, it's much easier in zsh to just use vi mode, ESC-k
  # (go to command mode and press k for up)
  fc -e -
}

