gui:
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      # - "#6970d7"
      # - "#850ccc"
      - "#ff0082"
      - bold
    inactiveBorderColor:
      - "#ffd700"
    optionsTextColor:
      - "#5260ff"
    selectedLineBgColor: # set to `default` to have no background colour
      - reverse
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
      - blue
      - magenta
  authorColors:
    # "chingyeow": "#ffd700"
    "tim goh": "#ff0082"
    "chingyeow": "#6970d7"
    "Alan Smithee": "#00ff00"
  branchColors:
    # "timg": "#458ac7"
    "timg": "#ff0082"
    "chingyeow": "#ffd700"
    "chingyeowp": "#6970d7"
