alias rapven="rapve -n"
alias rapved="rapve -d"
alias rapvea="rapve -a"
alias rapver="rapve -r"
alias rapves="rapve -s"
alias rapvee="rapve -e"

alias rapvl="rapv -l"
alias rapvs="rapv -s"
alias rapva="rapv -a"
alias rapvo="rapv -o"
alias rapval="rapv -al"
alias rapvsl="rapv -sl"
alias rapvol="rapv -ol"
