#!bin/zsh

function gr (){
  # fuzzy git review with delta use to review git diffs
  # j - preview down
  # k - preview up
  # t - preview half page down
  # n - preview half page up

  # gr <commit hash to compare with>
  # supply list of files to fzf
  # fzf preview with git delta
  local commitRange

  # if no args provided, compare with commone ancestor with main
  # the git diff command looks for changes from merg base to the SECOND commit
  # in <commit>...<commit>
  # if either commit is left out, head is used
  # refer to the git diff help page

  commitRange=${@:-"main..."}

  local preview="git diff $commitRange --color=always -- {-1} | delta --side-by-side -w ${FZF_PREVIEW_COLUMNS:-$COLUMNS}"
  git diff $commitRange --name-only | fzf --cycle --height '100%' --ansi --preview-window 'bottom,80%' --preview $preview \
    --bind 'h:preview-half-page-down' \
    --bind 't:preview-half-page-up' \
    --bind 'j:down' \
    --bind 'k:up' \
    # --bind 'h:up' \
}
