#!bin/zsh

function gr (){
  # fuzzy git review with delta use to review git diffs
  # gr - defaults to comparing main...
  # gr <commitRange> - eg gr <before commit hash>..<after commit hash>, eg gr abc~..abc

  # j - preview down
  # k - preview up
  # t - preview half page down
  # n - preview half page up

  # gr <commit hash to compare with>
  # supply list of files to fzf
  # fzf preview with git delta
  local commitRange

  # if no args provided, compare with commone ancestor with main
  # the git diff command looks for changes from merg base to the SECOND commit
  # in <commit>...<commit>
  # if either commit is left out, head is used
  # refer to the git diff help page

  # .. 
  # ... is gmb

  local commitStart=${1:-"main"}
  local commitRange="$commitStart..."

  local preview="git diff $commitRange --color=always -- {-1} | delta --side-by-side -w ${FZF_PREVIEW_COLUMNS:-$COLUMNS}"
  git diff $commitRange --name-only | fzf --cycle --height '100%' --ansi --preview-window 'bottom,80%' --preview $preview \
    --bind 'h:preview-half-page-down' \
    --bind 't:preview-half-page-up' \
    --bind 'j:down' \
    --bind 'k:up' \
    # --bind 'h:up' \
}
