#!bin/zsh

# generate the function files for autoloading
function _udc(){
  # read from the config.yml file and dynamically define the ud<key> functions
  # to fzf dir switch to the configured directories
  local outputFolder=$HOME/.local/lib/zsh/utilities/dir-switcher/out
  echo $fg[red] removing files in "$outputFolder" "..."
  [[ -n "$outputFolder" ]] && trash "$outputFolder/*"

  local configFile=$XDG_CONFIG_HOME/tg/dir-switcher/config.yml
  local config=$(yq eval '.keymaps' $configFile --output-format json | jq --compact-output '.[]')
  # for row in $config; do
  # while read loop splits only on newlines, unlike for do read which splits on any whitespace
  while read row; do
    local bindkey=$(jq --raw-output '.bindkey' <<< $row)
    local dir=$(jq '.dir' <<< $row)
    # https://github.com/stedolan/jq/issues/354#issuecomment-43147898
    # // is the jq alternative operator
    # empty is a jq builtin
    local depth=$(jq '.depth // empty' <<< $row)
    local glob=$(jq '.glob // empty' <<< $row)
    local showHidden=$(jq '.["show-hidden"] // empty' <<< $row)
    local showIgnore=$(jq '.["show-ignore"] // empty' <<< $row)
    local xargs=$(jq '.xargs // empty' <<< $row)
    # NOTE: running eval adds 1s to zsh startup 
    # instead, generate and autoload the functions
    echo "ud$bindkey() {ud $dir $depth $glob $showHidden $showIgnore $xargs}" > $outputFolder/ud$bindkey
  done <<< $config
}
