#!bin/zsh

function fsCheat(){
  local dirSwitcherConfigFile=$XDG_CONFIG_HOME/tg/dir-switcher/config.yml

    local jqQuery=$(cat <<-EOF
                               include "pad";
                               include "colour";
                               def configKeys:
                                 ["bindkey", "dir", "depth", "glob", "show-hidden", "show-ignore", "xargs"];
                               def convertToConfigHash:
                                 to_entries | map(.key = configKeys[.key]) | from_entries;
                               def convertArraysToConfigHash:
                                 if type == "object" then
                                    .
                                 else
                                   convertToConfigHash
                                   # .
                                 end;

                               .keymaps 
                               | map(convertArraysToConfigHash)
                               | map( "\(.bindkey | _ec(rpad(3;" "))) \(_bt(.dir))")
                               | .[]
EOF
)
  yq $dirSwitcherConfigFile --output-format=json | jq --raw-output -L "~/.config/jq" "$jqQuery" | fzf
}
